pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-github-release
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: GitHub Release
  desc: Publish files and artifacts to GitHub Releases
  type: publish
  image: plugins/drone-github-release
  labels:
    - github
    - release
